### ISSUE TITLE
Feature Restaurant

### ISSUE THREAD

**Issue by HadikaMalik** [HadikaMalik/React-Module-Project#23]
From React-Module-Project created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/React-Module-Project#8  

**Instructions:** 

Within the `src/App.js` file, render the `<Restaurant />` component (that is provided for you in `src/Restaurant.js`) underneath the `<Bookings />` component.

**Test:** 

- [ ] The restaurant orders should render on the page.

**Comment by BakhatBegum** [comment]
https://github.com/HadikaMalik/React-Module-Project/pull/45

**Comment by PERicci** [comment]
Review done, changes required.

**Comment by PERicci** [comment]
Pull request closed as the Restaurant component is already in the app.
